#!/bin/bash

if [ "$1" = "right" ]
then
    xrandr --output HDMI-1 --auto --right-of eDP-1
    echo "monitor set to the right"
fi

if [ "$1" = "left" ]
then
    xrandr --output HDMI-1 --auto --left-of eDP-1
    echo "monitor set to the left"
fi

if [ "$1" = "sameas" ]
then
    xrandr --output HDMI-1 --auto --same-as eDP-1
    echo "monitor set to the same as"
fi

if [ "$1" = "offhdmi" ]
then
    xrandr --auto
    echo "hdmi is off"
fi

if [ "$1" = "offlaptop" ]
then
	xrandr --output eDP-1 --off
	echo "laptop screen is off"
fi
