#!/bin/bash

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root, use sudo "$0" instead" 1>&2
   exit 1
fi

echo "started upgrading"

echo "running package updates"
sudo apt update

echo "running package upgrades"
sudo apt upgrade

echo "running dist-upgrade"
sudo apt dist-upgrade

echo "clean up"
sudo apt autoremove
